new stuff to work at BNL

diff --git a/bin/deswl-gen-meds-all b/bin/deswl-gen-meds-all
--- a/bin/deswl-gen-meds-all
+++ b/bin/deswl-gen-meds-all
@@ -9,7 +9,14 @@ medsconf=$1
 coadd_run=$2
 band=$3
 
+deswl-gen-meds-srclist --check $medsconf $coadd_run $band
+res=$?
+
+if [[ $res != "0" ]]; then
+    echo "error making srclist for $medsconf $coadd_run $band not creating other files"
+    exit 1
+fi
+
 deswl-gen-meds-script $medsconf $coadd_run $band
 deswl-gen-meds-pbs $medsconf $coadd_run $band
 deswl-gen-meds-wq $medsconf $coadd_run $band
-deswl-gen-meds-srclist $medsconf $coadd_run $band
diff --git a/bin/deswl-gen-meds-script b/bin/deswl-gen-meds-script
--- a/bin/deswl-gen-meds-script
+++ b/bin/deswl-gen-meds-script
@@ -18,7 +18,127 @@ parser = OptionParser(__doc__)
 parser.add_option('--vers',default='work',
                   help="Code version, default %default")
 
+
 _template="""#!/bin/bash
+# we write stdout from make-meds-input to the meds_input file; log messages
+# go to stderr
+#
+# make-cutouts only writes to stderr
+#
+# the exit status from those programs (the last to run) is written to the
+# meds_status file and becomes the exit status of this program.
+#
+# there should be no stdout from this script, only stderr
+#
+# in production this script is called by a pbs submit script and the
+# stderr is written to a log file (meds_log)
+
+#nsetup_ess
+module unload shapelets && module load shapelets/{vers}
+module unload meds && module load meds/{vers}
+
+magzp_ref={magzp_ref}
+coadd_file="{coadd_image}"
+coaddseg_file="{coadd_seg}"
+coaddcat_file="{coadd_cat}"
+coadd_srclist="{meds_srclist}"
+cutout_file="{meds_file}"
+meds_input="{meds_input}"
+medsconf={medsconf}
+meds_status="{meds_status}"
+
+min_boxsize={min_boxsize}
+max_boxsize={max_boxsize}
+
+# temporary directory and filenames
+cutout_file_bname=$(basename $cutout_file)
+
+db=$(echo $cutout_file_bname | sed 's/\.fits\.fz//')
+tmpdir="/data/esheldon/tmp/meds-tmp-$db-$RANDOM"
+mkdir -p "$tmpdir"
+
+tmpfile_fz="$tmpdir/$cutout_file_bname"
+tmpfile_uc=$(echo $tmpfile_fz | sed 's/\.fz//')
+
+echo "tmp file fz: $tmpfile_fz"
+echo "tmp file uc: $tmpfile_uc"
+
+
+# make final output directory
+output_dir=$(dirname "$cutout_file")
+mkdir -p "$output_dir"
+
+# remove existing file
+if [[ -e "$cutout_file" ]]; then
+    rm -v "$cutout_file"
+fi
+
+echo "creating meds input $meds_input"
+make-meds-input "$coaddcat_file" $min_boxsize $max_boxsize > "$meds_input"
+
+exit_status=$?
+if [[ $exit_status == "0" ]]; then
+
+    # keywords after cutout_file= are just extra medatdata to be written into
+    # the metadata table; they are not used by the code
+
+    cmd="
+    make-cutouts
+        magzp_ref=$magzp_ref
+        coadd_file=$coadd_file
+        coaddseg_file=$coaddseg_file
+        cat_file=$meds_input
+        coadd_srclist=$coadd_srclist
+        cutout_file=$tmpfile_uc
+        medsconf=$medsconf
+        coaddcat_file=$coaddcat_file
+        min_boxsize=$min_boxsize
+        max_boxsize=$max_boxsize
+    "
+
+    $cmd
+
+    exit_status=$?
+    if [[ $exit_status == "0" ]]; then
+        size=$(du -h "$tmpfile_uc" | awk '{{print $1}}')
+        echo "size of uncompressed file: $size"
+        echo "fpacking to $tmpfile_fz"
+        fpack -t {fpack_dim0},{fpack_dim1} "$tmpfile_uc" 
+
+        ok="yes"
+        exit_status=$?
+        if [[ $exit_status == "0" ]]; then
+            if [[ ! -e "$tmpfile_fz" ]]; then
+                ok="no"
+                echo "compressed cutout file not made $tmpfile_fz"
+                echo "copying uncompressed file $tmpfile_uc"
+                exit_status=1
+            fi
+        fi
+
+        if [[ $ok == "yes" ]]; then
+            cp -v "$tmpfile_fz" "$output_dir/"
+        else
+            cp -v "$tmpfile_uc" "$output_dir/"
+        fi
+    fi
+fi
+
+echo "cleaning up tmpdir: $tmpdir"
+rm -rf $tmpdir
+
+mess="writing status $exit_status to meds_status:
+    $meds_status"
+echo $mess
+
+echo "exit_status: $exit_status" > "$meds_status"
+
+echo "time: $SECONDS"
+exit $exit_status
+"""
+
+
+_template_old="""#!/bin/bash
 # we write stdout from make-meds-input to the meds_input file; log messages
 # go to stderr
 #
@@ -107,6 +227,8 @@ mess="writing status $exit_status to meds_status:
 echo $mess
 
 echo "exit_status: $exit_status" > "$meds_status"
+
+echo "time: $SECONDS"
 exit $exit_status
 """
 
@@ -171,12 +293,12 @@ def main():
                       tilename=cf['tilename'],
                       band=band)
 
-    meds_file_fz=df.url(medsconf=medsconf,
-                        type='meds',
-                        coadd_run=coadd_run,
-                        tilename=cf['tilename'],
-                        band=band)
-    meds_file_uc = meds_file_fz.replace('.fz','')
+    meds_file=df.url(medsconf=medsconf,
+                     type='meds',
+                     coadd_run=coadd_run,
+                     tilename=cf['tilename'],
+                     band=band)
+    #meds_file_uc = meds_file_fz.replace('.fz','')
     meds_status=df.url(medsconf=medsconf,
                        type='meds_status',
                        coadd_run=coadd_run,
@@ -194,8 +316,7 @@ def main():
                           meds_srclist=meds_srclist,
                           min_boxsize=conf['min_boxsize'],
                           max_boxsize=conf['max_boxsize'],
-                          meds_file_uc=meds_file_uc,
-                          meds_file_fz=meds_file_fz,
+                          meds_file=meds_file,
                           meds_status=meds_status,
                           fpack_dim0=conf['fpack_dims'][0],
                           fpack_dim1=conf['fpack_dims'][1])
@@ -206,7 +327,7 @@ def main():
                        tilename=cf['tilename'],
                        band=band)
 
-    make_dirs(script_file, meds_file_uc)
+    make_dirs(script_file, meds_file)
     
     print script_file
     with open(script_file,'w') as fobj:
