script to call make-meds-input and make-cutouts

diff --git a/bin/deswl-gen-meds-script b/bin/deswl-gen-meds-script
--- a/bin/deswl-gen-meds-script
+++ b/bin/deswl-gen-meds-script
@@ -1,8 +1,10 @@
 #!/usr/bin/env python
 """
-    %prog [options] run band cutout_size
+    %prog [options] meds_config coadd_run band
 
-Generate shell script to run make-cutouts.
+Generate shell script to run make-meds-input and make-cutouts.
+
+meds_config is a meds config id, e.g. meds001
 """
 
 import os,sys
@@ -20,22 +22,38 @@ parser.add_option('--vers',default='work',
 
 _template="""
 module unload shapelets-{whose} && module load shapelets-{whose}/{vers}
+module unload deswl-{whose} && module load deswl-{whose}/{vers}
 
-coaddimage_file="{coadd_image}"
+coadd_file="{coadd_image}"
 coaddcat_file="{coadd_cat}"
-coadd_srclist="{meds_input}"
-cutout_size={cutout_size}
+coadd_srclist="{meds_srclist}"
 cutout_file="{meds_file}"
+meds_input="{meds_input}"
+
+min_boxsize={min_boxsize}
+max_boxsize={max_boxsize}
 
 d=$(dirname "$cutout_file")
 mkdir -p "$d"
 
-make-cutouts \\
-    coaddimage_file="$coaddimage_file" \\
-    coaddcat_file="$coaddcat_file"     \\
-    coadd_srclist="$coadd_srclist"     \\
-    cutout_size="$cutout_size"         \\
+echo "creating meds input $meds_input"
+make-meds-input "$coaddcat_file" $min_boxsize $max_boxsize > "$meds_input"
+
+if [[ $? != "0" ]]; then
+    echo "failed to make meds input file"
+    exit 1
+fi
+
+make-cutouts                         \\
+    coadd_file="$coadd_file"         \\
+    cat_file="$meds_input"           \\
+    coadd_srclist="$coadd_srclist"   \\
     cutout_file="$cutout_file"
+
+if [[ $? != "0" ]]; then
+    echo "failed to make meds file"
+    exit 2
+fi
 """
 
 def make_dirs(script_file, meds_file):
@@ -55,9 +73,11 @@ def main():
         parser.print_help()
         sys.exit(45)
 
-    coadd_run=args[0]
-    band=args[1]
-    cutout_size=int(args[2])
+    meds_config_id=args[0]
+    coadd_run=args[1]
+    band=args[2]
+
+    conf=deswl.files.read_meds_config(meds_config_id)
 
     df=desdb.files.DESFiles()
     cf=desdb.files.Coadd(run=coadd_run,
@@ -72,6 +92,11 @@ def main():
                      run=coadd_run,
                      tilename=cf['tilename'],
                      band=band)
+
+    meds_srclist=df.url(type='meds_srclist',
+                        run=coadd_run,
+                        tilename=cf['tilename'],
+                        band=band)
     meds_input=df.url(type='meds_input',
                       run=coadd_run,
                       tilename=cf['tilename'],
@@ -87,8 +112,11 @@ def main():
                           coadd_image=coadd_image,
                           coadd_cat=coadd_cat,
                           meds_input=meds_input,
-                          cutout_size=cutout_size,
+                          meds_srclist=meds_srclist,
+                          min_boxsize=conf['min_boxsize'],
+                          max_boxsize=conf['max_boxsize'],
                           meds_file=meds_file)
+
     script_file=df.url(type='meds_script',
                        run=coadd_run,
                        tilename=cf['tilename'],
